= Literature Review

== UQ Method Categories

The LM-Polygraph benchmark @Vashurin_2025 evaluates 29 UQ methods on natural language generation and organizes them into four categories:

- *Information-Theoretic:* compute uncertainty from the model's token-level probability distribution. Examples include Maximum Sequence Probability, Perplexity, and Mean Token Entropy @Fomicheva.
- *Sample Diversity:* generate multiple completions for the same prompt and measure their disagreement. Consistent outputs indicate higher confidence. Examples include Semantic Entropy @kuhn2023semanticuncertaintylinguisticinvariances, Degree Matrix, and Sum of Eigenvalues of the Graph Laplacian @lin2024generatingconfidenceuncertaintyquantification.
- *Density-based:* compare a generated output's embedding against a reference distribution of correct examples. Outputs far from the distribution are flagged as uncertain. Examples are Mahalanobis distance (MD) @lee2018simpleunifiedframeworkdetecting and Robust density estimation (RDE) @yoo-etal-2022-detection.
- *Reflexive:* ask the model to evaluate its own confidence directly (e.g., "Are you certain about your last response?"). The $p("True")$ method @kadavath2022languagemodelsmostlyknow is an example.

Each category comes with its strengths and weaknesses (according to @Vashurin_2025):

#figure(
  table(
    columns: (auto, 1.5fr, auto, 2.5fr, 2.5fr),
    align: (left, center, center, left, left),

    table.header(
      [*Category*], [*Access*], [*Compute*], [*Strengths*], [*Weaknesses*]
    ),

    [_Information-Theoretic_],
    [White-Box],
    [Low],
    [Fast, theoretically grounded, provides token-level scores],
    [Requires internal model access. Can be naive to semantic meaning],

    [_Sample Diversity_],
    [Black-Box],
    [High],
    [Model-agnostic. Captures semantic uncertainty],
    [Requires generating many outputs. Clustering can be complex and slow],

    [_Density-Based_],
    [Black-Box],
    [Medium],
    [Good at detecting outputs that are structurally or stylistically unusual],
    [Requires a high-quality reference dataset: performance depends heavily on the embedding space],

    [_Reflexive_],
    [Black-Box],
    [Low],
    [Simple to implement],
    [Highly unreliable: models are often overconfident and poor at self-assessment],
  ),
  caption: [Comparison of Uncertainty Quantification Method Categories],
)<uq_taxonomy>

== Code Hallucination Taxonomies

Several recent works classify the types of errors that occur when large language models generate code. While each proposes a distinct taxonomy, their categories overlap considerably. Understanding these taxonomies is important for uncertainty quantification, as different types of hallucinations are caught by different detection strategies.

*CodeMirage* @agarwal2025codemiragehallucinationscodegenerated analyzed 1,137 Python code snippets generated by GPT-3.5 on HumanEval and MBPP benchmarks. The authors annotated each snippet with one of five defect types: logical errors (the code runs but solves the wrong problem), syntactic incorrectness (the code does not compile), dead or unreachable code (segments that serve no purpose), robustness issues (the code fails on edge cases or raises exceptions), and security vulnerabilities (the code has exploitable flaws or memory leaks). These defect types appeared in roughly equal proportions in their dataset.

*HalluCode* @liu2024HalluCode classifies hallucinations based on what the code conflicts with, rather than the technical nature of the defect. This taxonomy, developed for Python and Java tasks, defines three broad categories with twelve subcategories. Requirement conflicts (39.6%) cover cases where the code does something other than what was specified, with behavior conflicts (35.4%) as the largest subcategory. Knowledge hallucinations (34.9%) capture cases where the code contradicts real-world knowledge, such as incorrect use of library APIs (25.99%) or algorithmic conventions. Code inconsistency (25.5%) refers to internal contradictions, like undefined variables or redundant statements. The study found that model-related factors account for the majority (80.86%) of hallucinations and that larger models tend to hallucinate less.

*CodeHalu* @tian2025codehaluinvestigatingcodehallucinations organizes errors by their source. Mapping hallucinations arise when the model incorrectly maps between the problem description and code variables or functions. Naming hallucinations involve the use of incorrect identifiers. Resource hallucinations refer to references to non-existent libraries or functions. Logic hallucinations involve flawed algorithmic reasoning. These four categories are further divided into eight subcategories and are validated by executing the generated code.

These taxonomies overlap but emphasize different aspects of the same underlying problem. @hallucination_taxonomy combines them into an overview:

#figure(
  table(
    columns: (auto, auto),
    align: left,

    table.header(
      [*Hallucination Types*],
      [*Description*],
    ),

    [
      - Logical Error @agarwal2025codemiragehallucinationscodegenerated
      - Intent Conflicting @liu2024HalluCode
      - Logic Hallucinations @tian2025codehaluinvestigatingcodehallucinations
    ],
    [The code is syntactically valid but fails to meet the problem's requirements or contains flawed logic],

    [
      - Syntactic Incorrectness @agarwal2025codemiragehallucinationscodegenerated
      - Dead or Unreachable Code @agarwal2025codemiragehallucinationscodegenerated
      - Naming Hallucinations @tian2025codehaluinvestigatingcodehallucinations
      - Context Deviation @liu2024HalluCode
    ],
    [The code is malformed, uses wrong identifiers, contains non-functional or repetitive segments, or cannot be compiled],

    [
      - Robustness Issue @agarwal2025codemiragehallucinationscodegenerated
    ],
    [The code compiles but fails at runtime on edge cases or lacks exception handling],

    [
      - Security Vulnerabilities @agarwal2025codemiragehallucinationscodegenerated
      - Knowledge Conflicting @liu2024HalluCode
      - Mapping Hallucinations @tian2025codehaluinvestigatingcodehallucinations
      - Resource Hallucinations @tian2025codehaluinvestigatingcodehallucinations
    ],
    [The code misuses variables, external APIs, or libraries, or calls non-existent resources, leading to errors or security flaws],
  ),
  caption: [Code Hallucination Taxonomy],
)<hallucination_taxonomy>

As @hallucination_taxonomy shows, code hallucinations differ from general text generation errors. Methods from natural language generation (NLG) require adaptation to work on code.

== Evaluating Uncertainty Quantification Methods

Measuring UQ performance is challenging. Literature uses several approaches:

- Rank correlation (Spearman's $ρ$) between uncertainty scores and output quality metrics such as ROUGE or BLEU @Fomicheva @compareUQmetrics. These metrics reveal little about practical performance, and n-gram metrics often miss semantic quality.
- Binary classification (correct vs. incorrect output) evaluated with AUROC or PR-AUC @Vashurin_2025 @ling-etal-2024-uncertainty @compareUQmetrics. This approach requires an arbitrary correctness threshold, making cross-study comparison difficult.

This thesis uses both PR-AUC and the Prediction Rejection Ratio (PRR) @malinin2017prr, with PR-AUC as the primary metric. PRR is the standard in LM-Polygraph @Vashurin_2025 and earlier work @malinin2021uncertainty. Both are defined in @evaluation_metrics.


== Uncertainty Quantification for Code

UnCert-CoT @zhu2025uncertaintyguidedchainofthoughtcodegeneration uses token entropy to switch from direct generation to Chain-of-Thought reasoning when uncertainty is high. AdaDec @he2025adadec uses token-level entropy to pause decoding and rerank candidate tokens.

Token-level signals often fail for code because syntactically different programs can do the same thing. Recent work clusters outputs by behavior rather than text.

Ravuri and Amarasinghe @Ravuri2025EliminatingHE propose functional clustering, arguing that text embeddings miss small errors, such as a swapped operator, that can break code. Their method generates programs and test inputs, runs them in a sandbox, and groups programs with identical input-output behavior. The size of the largest group becomes the confidence score. On LiveCodeBench, this reduced error rates from about 65% to 2%, while token-probability scores could not reliably separate correct from incorrect outputs.

Sharma and David @sharma2025assessingcorrectnessllmbasedcode propose symbolic clustering, which goes beyond unit tests by treating inputs as abstract symbols and generating code execution traces via symbolic execution. They group programs whose traces match. In testing several standard UQ approaches on code, they found Pearson correlations with correctness near zero: text-similarity methods reached $r = -0.04$ to $-0.21$ (all $p > 0.08$), and token log-probabilities $r = 0.09$ to $0.18$ ($p > 0.38$), none statistically significant. Only symbolic clustering achieved meaningful correlations ($r = -0.40$ to $-0.56$, $p < 0.001$), with a false-positive rate below 0.02%.

Both functional and symbolic clustering are sample-diversity methods like Semantic Entropy and are computationally expensive.

Other approaches use classical code metrics as proxies: compiler feedback @wang2022compilableneuralcodegeneration, static code quality analysis @dolcetti2025helpingllmsimprovecode, and pass rates of generated unit tests @liu2025llmpoweredtestcasegeneration.
